### PR TITLE
Switch to traefik from nginx, use TLS in auth

### PR DESCRIPTION
**Pull request by anukul**
See commit note

### CODE REVIEW

**Comment by williammartin** [comment]
> We need the edge router to make HTTPS requests to auth

Why? I thought we discussed this wasn't necessary because nginx would pass through the `secure` cookie and only the browser cared about the connection being TLS secured?

Talk me through the pros and cons of each approach?

**Comment by anukul** [comment]
I decided to run an HTTPS server on `auth` so that we could write an acceptance test for the `Secure` cookie. In the alternative approach, this wasn't possible (as I had found out during our discussion).

Now, if nginx makes an HTTP request to `auth`, the response is:

> Client sent an HTTP request to an HTTPS server

**Comment by williammartin** [comment]
I'm not following sorry. We had the following discussion:

image

This lead me to believe that the following would work:

```
 - [ Client ] -- HTTPS --> [ Nginx Controller ] -- HTTP --> [ Auth Server ]
```

I understand that for the acceptance tests to work, we needed the ability to have the auth server configurable for TLS. Does that mean it must also be configured for TLS when deployed into k8s, if the controller can handle termination.

> Client sent an HTTP request to an HTTPS server

This looks like the kind of message we would get if we were running the auth server with TLS configured in the cluster. I'm asking whether we need to run the auth server with TLS configured at all in the cluster if the controller handles termination.

There may be a good reason to (for example, to stop snooping network traffic) in the cluster if we had a vulnerability but I'd rather we made that decision consciously, and I'm not sure that's what's happening here.

**Comment by anukul** [comment]
I think we’re on the same page now.

I was trying to keep things consistent between tests and production.

If not, and we choose to run the server configured with TLS **only** in tests, I can add the appropriate condition accordingly.

**Comment by williammartin** [comment]
> I was trying to keep things consistent between tests and production.

And I think that's valuable, but also worth considering that it makes the `auth` server inconsistent with the other components.

> If not, and we choose to run the server configured with TLS only in tests, I can add the appropriate condition accordingly.

Well, what do you think? Are there other pros and cons than what I noted above?

**Comment by anukul** [comment]
> Are there other pros and cons than what I noted above?

I can't think of anything else, but I'm also not particular about either approach over the other. 🤔

**Pull request closed without merging**
